apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hello-cpp
  name: hello-cpp-exec
spec:
  containers:
  - name: hello-cpp
    image: quay.io/mcochran/cpp-hello
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
  restartPolicy: Never
